### ISSUE TITLE
only maindomain color bold

### ISSUE THREAD

**Issue by Zitronella** [sdavidg/firefoxChromeScripts#3]
Thanks for this dav_LinkifiesLocationBar.uc.js script. It works good. I have no issue but only a wish, hope this is the right place for it. I only want the main domain to be bold and colored. I do not want any other functions at all. (Via userChrome.css this is not possible to realize)
Is there a shorter code for this that only does this wish? Unfortunately I do not know code at all.
Is it possible to post the code for this here?
Thanks and greetings from germany
Zitronella 
(sorry for my bad english)

**Comment by sdavidg** [comment]
lease, try the new version and change the variable `pathnameArrow = true` to `pathnameArrow = false` in the source code. The other functions are necessary because this is a DOM element over the original urlbar

**Comment by Zitronella** [comment]
Thanks, but this does not help me so much, it only remove pathnameArrow.

**Comment by Speravir** [comment]
While I l do not open this issue ticket again could you, please, take a look on the changed script [I posted in camp-firefox.de on 7 February 2021](https://www.camp-firefox.de/forum/thema/131997-weitere-userchromeskript-ressource-firefoxchromescripts/?postID=1164024#post1164024)? I think this is what @Zitronella wanted.

I may have disabled too much because of my lack of Javascript knowledge , but you should get the idea. It worked here in tests. If you’d change your code to insert this option a note would be necessary for selecting the address bar afterwards: With disabled event listeners this is only possible with right mouse click and F6 key.

_(In the Camp-Firefox.de thread [Weitere UserChromeskript-Ressource „firefoxChromeScripts“](https://www.camp-firefox.de/forum/thema/131997-weitere-userchromeskript-ressource-firefoxchromescripts/) I made some advocacy for your script resource.)_

**Comment by sdavidg** [comment]
`With disabled event listeners this is only possible with right mouse click and F6 key.` You have deleted too many events :wink:

I'll take a look.

And thank you for your comments, I am glad you found it useful
